localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=testando123
    - POSTGRES_PASSWORD=senha123
    - POSTGRES_DB=database123

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=testando123
    - POSTGRES_PASSWORD=senha123
    - POSTGRES_DB=database123
